name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Generate Android Project Files
        run: flutter create --project-name fayyad_glass --platforms=android .

      - name: Create local.properties
        run: echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties

      - name: Restore Google Services
        run: git checkout android/app/google-services.json || true

      - name: Update minSdkVersion to 21
        run: |
          sed -i 's/minSdkVersion.*/minSdkVersion 21/g' android/app/build.gradle || true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK Release
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
